
services:
  app:
    build: .
    image: finradar-panel:latest
    container_name: finradar_app
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    image: finradar-panel:latest
    container_name: finRadar_worker
    command: ["python", "app/workers/worker.py"]
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: finRadardb
      POSTGRES_USER: finradar
      POSTGRES_PASSWORD: finradarpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
